-- vimesimal — dark theme on kitty's transparent black, with bright
-- Linux-console syntax colors. Syntax groups use the roles defined in
-- lua/vimesimal/palette.lua (p.keyword, p.type, …).
-- Highlight backgrounds (search, selection, menu) stay dark or colored,
-- never white, so the cursor stays visible on them.

vim.cmd("highlight clear")
vim.o.background = "dark"
vim.g.colors_name = "vimesimal"

local p = require("vimesimal.palette")
local none = "NONE"

local groups = {
  -- Editor UI
  Normal = { fg = p.white, bg = none },
  NormalNC = { link = "Normal" },
  -- Floats are transparent like the editor; the border marks their edge
  NormalFloat = { fg = p.white, bg = none },
  FloatBorder = { fg = p.faint, bg = none },
  FloatTitle = { fg = p.cyan, bg = none, bold = true },
  FloatFooter = { fg = p.cyan, bg = none },
  NonText = { fg = p.guide },
  Whitespace = { fg = p.guide },
  SpecialKey = { fg = p.guide },
  EndOfBuffer = { fg = p.guide },
  Conceal = { fg = p.faint },
  LineNr = { fg = p.faint },
  CursorLineNr = { fg = p.yellow, bg = p.panel, bold = true },
  CursorLine = { bg = p.panel },
  CursorColumn = { bg = p.panel },
  ColorColumn = { bg = p.panel },
  SignColumn = { bg = none },
  FoldColumn = { fg = p.faint },
  Folded = { fg = p.mute, bg = p.panel },
  WinSeparator = { fg = p.guide },
  StatusLine = { fg = p.white, bg = p.panel },
  StatusLineNC = { fg = p.faint, bg = p.panel },
  TabLine = { fg = p.faint, bg = p.panel },
  TabLineFill = { bg = p.panel },
  TabLineSel = { fg = p.white, bg = p.select, bold = true },
  WinBar = { fg = p.dim },
  Visual = { bg = p.select },
  Search = { fg = p.black, bg = p.yellow },
  IncSearch = { fg = p.black, bg = p.cyan, bold = true },
  CurSearch = { link = "IncSearch" },
  Substitute = { fg = p.black, bg = p.red },
  MatchParen = { fg = p.yellow, bg = p.guide, bold = true },
  Pmenu = { fg = p.dim, bg = none },
  PmenuSel = { fg = p.white, bg = p.select, bold = true },
  PmenuSbar = { bg = p.line },
  PmenuThumb = { bg = p.mute },
  PmenuKind = { fg = p.cyan, bg = none },
  PmenuExtra = { fg = p.mute, bg = none },
  WildMenu = { link = "PmenuSel" },
  Title = { fg = p.cyan, bold = true },
  Directory = { fg = p.cyan },
  ModeMsg = { fg = p.white, bold = true },
  MoreMsg = { fg = p.green },
  Question = { fg = p.green },
  ErrorMsg = { fg = p.red, bold = true },
  WarningMsg = { fg = p.yellow },
  QuickFixLine = { bg = p.select },
  SpellBad = { undercurl = true, sp = p.red },
  SpellCap = { undercurl = true, sp = p.yellow },
  SpellRare = { undercurl = true, sp = p.magenta },
  SpellLocal = { undercurl = true, sp = p.cyan },
  DiffAdd = { bg = "#003300" },
  DiffChange = { bg = "#1a1a44" },
  DiffDelete = { fg = p.red, bg = "#330000" },
  DiffText = { bg = "#33337a" },
  -- Claude quick-answer edits: removed lines red, added/changed lines green
  VimesimalDiffAdd = { fg = p.green, bg = "#0f2e0f" },
  VimesimalDiffDelete = { fg = p.red, bg = "#3a0f0f" },
  Cursor = { reverse = true },

  -- Syntax
  Comment = { fg = p.comment, italic = true },
  SpecialComment = { fg = p.comment, italic = true },
  Todo = { fg = p.black, bg = p.yellow, bold = true },
  Constant = { fg = p.number },
  Number = { fg = p.number },
  Float = { fg = p.number },
  Boolean = { fg = p.number },
  String = { fg = p.string },
  Character = { fg = p.string },
  Identifier = { fg = p.white },
  Function = { fg = p.func, bold = true },
  Statement = { fg = p.keyword, bold = true },
  Conditional = { fg = p.keyword, bold = true },
  Repeat = { fg = p.keyword, bold = true },
  Label = { fg = p.keyword },
  Keyword = { fg = p.keyword, bold = true },
  Exception = { fg = p.keyword, bold = true },
  Operator = { fg = p.operator },
  Delimiter = { fg = p.gray },
  PreProc = { fg = p.preproc },
  Include = { fg = p.preproc },
  Define = { fg = p.preproc },
  Macro = { fg = p.preproc },
  PreCondit = { fg = p.preproc },
  Type = { fg = p.type },
  StorageClass = { fg = p.type },
  Structure = { fg = p.type },
  Typedef = { fg = p.type },
  Special = { fg = p.special },
  SpecialChar = { fg = p.special },
  Tag = { fg = p.special },
  Debug = { fg = p.special },
  Underlined = { fg = p.cyan, underline = true },
  Ignore = { fg = p.faint },
  Error = { fg = p.red, bold = true },
  Added = { fg = p.green },
  Changed = { fg = p.cyan },
  Removed = { fg = p.red },

  -- Tree-sitter
  ["@variable"] = { fg = p.white },
  ["@variable.builtin"] = { fg = p.special },
  ["@variable.parameter"] = { fg = p.param, italic = true },
  ["@variable.member"] = { fg = p.member },
  ["@property"] = { fg = p.member },
  ["@constant"] = { link = "Constant" },
  ["@constant.builtin"] = { fg = p.number },
  ["@constant.macro"] = { fg = p.preproc },
  ["@module"] = { fg = p.type },
  ["@label"] = { link = "Label" },
  ["@string"] = { link = "String" },
  ["@string.escape"] = { fg = p.escape },
  ["@string.special"] = { fg = p.format },
  ["@character"] = { link = "Character" },
  ["@number"] = { link = "Number" },
  ["@boolean"] = { link = "Boolean" },
  ["@type"] = { link = "Type" },
  ["@type.builtin"] = { fg = p.type },
  ["@type.definition"] = { fg = p.type },
  ["@constructor"] = { fg = p.type }, -- QML components (Rectangle {), Python classes
  ["@attribute"] = { fg = p.special },
  ["@function"] = { link = "Function" },
  ["@function.call"] = { fg = p.func },
  ["@function.builtin"] = { fg = p.func },
  ["@function.macro"] = { fg = p.preproc },
  ["@keyword"] = { link = "Keyword" },
  ["@keyword.return"] = { fg = p.keyword, bold = true },
  ["@keyword.directive"] = { fg = p.preproc },
  ["@keyword.directive.define"] = { fg = p.preproc },
  ["@keyword.import"] = { fg = p.preproc },
  ["@keyword.modifier"] = { fg = p.type },
  ["@keyword.type"] = { fg = p.type },
  ["@operator"] = { link = "Operator" },
  ["@punctuation"] = { fg = p.gray },
  ["@punctuation.bracket"] = { fg = p.white },
  ["@tag"] = { fg = p.type }, -- JSX components (<Image>), like QML components
  ["@tag.builtin"] = { fg = p.func }, -- HTML elements (<div>, <main>)
  ["@tag.attribute"] = { fg = p.member }, -- className, src, like properties
  ["@tag.delimiter"] = { fg = p.gray }, -- < > />
  ["@comment"] = { link = "Comment" },
  ["@comment.todo"] = { link = "Todo" },

  -- NASM (regex syntax: syntax/nasm.vim leaves registers unlinked)
  nasmGen08Register = { fg = p.register },
  nasmGen16Register = { fg = p.register },
  nasmGen32Register = { fg = p.register },
  nasmGen64Register = { fg = p.register },
  nasmExtRegister = { fg = p.register },
  nasmSegRegister = { fg = p.register },
  nasmSpcRegister = { fg = p.register },
  nasmFpuRegister = { fg = p.register },
  nasmMmxRegister = { fg = p.register },
  nasmAvxRegister = { fg = p.register },
  nasmCtrlRegister = { fg = p.register },
  nasmDebugRegister = { fg = p.register },
  nasmTestRegister = { fg = p.register },
  nasmLabel = { fg = p.func },
  nasmLocalLabel = { fg = p.func },

  -- LSP
  ["@lsp.type.macro"] = { fg = p.preproc },
  ["@lsp.type.enumMember"] = { fg = p.number },
  LspReferenceText = { bg = p.line },
  LspReferenceRead = { bg = p.line },
  LspReferenceWrite = { bg = p.line, underline = true },
  LspInlayHint = { fg = p.faint, italic = true },
  DiagnosticError = { fg = p.red },
  DiagnosticWarn = { fg = p.yellow },
  DiagnosticInfo = { fg = p.cyan },
  DiagnosticHint = { fg = p.gray },
  DiagnosticOk = { fg = p.green },
  DiagnosticVirtualTextError = { fg = p.red, italic = true },
  DiagnosticVirtualTextWarn = { fg = p.yellow, italic = true },
  DiagnosticVirtualTextInfo = { fg = p.cyan, italic = true },
  DiagnosticVirtualTextHint = { fg = p.gray, italic = true },
  DiagnosticUnderlineError = { undercurl = true, sp = p.red },
  DiagnosticUnderlineWarn = { undercurl = true, sp = p.yellow },
  DiagnosticUnderlineInfo = { undercurl = true, sp = p.cyan },
  DiagnosticUnderlineHint = { undercurl = true, sp = p.gray },

  -- Plugins
  BlinkCmpLabelMatch = { fg = p.yellow, bold = true },
  BlinkCmpKind = { fg = p.cyan },
  BlinkCmpMenuBorder = { link = "FloatBorder" },
  BlinkCmpDocBorder = { link = "FloatBorder" },
  IblIndent = { fg = p.guide },
  IblScope = { fg = p.faint },
  GitSignsAdd = { fg = p.green },
  GitSignsChange = { fg = p.cyan },
  GitSignsDelete = { fg = p.red },
  NvimTreeNormal = { bg = none },
  NvimTreeWinSeparator = { link = "WinSeparator" },
  NvimTreeRootFolder = { fg = p.yellow, bold = true },
  NvimTreeFolderName = { fg = p.cyan },
  NvimTreeOpenedFolderName = { fg = p.cyan, bold = true },
  NvimTreeFolderIcon = { fg = p.cyan },
  NvimTreeIndentMarker = { fg = p.guide },
  FzfLuaBorder = { link = "FloatBorder" },
  FlashLabel = { fg = p.black, bg = p.magenta, bold = true }, -- press this to jump
  FlashMatch = { fg = p.white, bg = p.select },
  FlashCurrent = { fg = p.black, bg = p.yellow },
  FlashBackdrop = { fg = p.faint },
}

for name, spec in pairs(groups) do
  vim.api.nvim_set_hl(0, name, spec)
end
