-- vimesimal — dark theme on kitty's transparent black, with full-color syntax.
-- Background is NONE so kitty's background_opacity shows through.
-- Highlight backgrounds (search, selection, menu) stay dark or colored,
-- never white, so the cursor stays visible on them.

vim.cmd("highlight clear")
vim.o.background = "dark"
vim.g.colors_name = "vimesimal"

local p = require("vimesimal.palette")
local none = "NONE"

local groups = {
  -- Editor UI
  Normal = { fg = p.white, bg = none },
  NormalNC = { link = "Normal" },
  NormalFloat = { fg = p.dim, bg = p.panel },
  FloatBorder = { fg = p.faint, bg = p.panel },
  FloatTitle = { fg = p.blue, bg = p.panel, bold = true },
  NonText = { fg = p.guide },
  Whitespace = { fg = p.guide },
  SpecialKey = { fg = p.guide },
  EndOfBuffer = { fg = p.guide },
  Conceal = { fg = p.faint },
  LineNr = { fg = p.faint },
  CursorLineNr = { fg = p.yellow, bg = p.panel, bold = true },
  CursorLine = { bg = p.panel },
  CursorColumn = { bg = p.panel },
  ColorColumn = { bg = p.panel },
  SignColumn = { bg = none },
  FoldColumn = { fg = p.faint },
  Folded = { fg = p.mute, bg = p.panel },
  WinSeparator = { fg = p.guide },
  StatusLine = { fg = p.white, bg = p.panel },
  StatusLineNC = { fg = p.faint, bg = p.panel },
  TabLine = { fg = p.faint, bg = p.panel },
  TabLineFill = { bg = p.panel },
  TabLineSel = { fg = p.white, bg = p.select, bold = true },
  WinBar = { fg = p.dim },
  Visual = { bg = p.select },
  Search = { fg = p.black, bg = p.yellow },
  IncSearch = { fg = p.black, bg = p.orange, bold = true },
  CurSearch = { link = "IncSearch" },
  Substitute = { fg = p.black, bg = p.red },
  MatchParen = { fg = p.yellow, bg = p.guide, bold = true },
  Pmenu = { fg = p.dim, bg = p.panel },
  PmenuSel = { fg = p.white, bg = p.select, bold = true },
  PmenuSbar = { bg = p.line },
  PmenuThumb = { bg = p.mute },
  PmenuKind = { fg = p.blue, bg = p.panel },
  PmenuExtra = { fg = p.mute, bg = p.panel },
  WildMenu = { link = "PmenuSel" },
  Title = { fg = p.blue, bold = true },
  Directory = { fg = p.blue },
  ModeMsg = { fg = p.white, bold = true },
  MoreMsg = { fg = p.green },
  Question = { fg = p.green },
  ErrorMsg = { fg = p.red, bold = true },
  WarningMsg = { fg = p.yellow },
  QuickFixLine = { bg = p.select },
  SpellBad = { undercurl = true, sp = p.red },
  SpellCap = { undercurl = true, sp = p.yellow },
  SpellRare = { undercurl = true, sp = p.purple },
  SpellLocal = { undercurl = true, sp = p.blue },
  DiffAdd = { bg = "#1e2e1e" },
  DiffChange = { bg = "#1e2433" },
  DiffDelete = { fg = p.red, bg = "#2e1e1e" },
  DiffText = { bg = "#2e3a55" },
  Cursor = { reverse = true },

  -- Syntax
  Comment = { fg = p.mute, italic = true },
  SpecialComment = { fg = p.faint, italic = true },
  Todo = { fg = p.black, bg = p.yellow, bold = true },
  Constant = { fg = p.orange },
  Number = { fg = p.orange },
  Float = { fg = p.orange },
  Boolean = { fg = p.orange },
  String = { fg = p.green },
  Character = { fg = p.green },
  Identifier = { fg = p.white },
  Function = { fg = p.blue, bold = true },
  Statement = { fg = p.purple, bold = true },
  Conditional = { fg = p.purple, bold = true },
  Repeat = { fg = p.purple, bold = true },
  Label = { fg = p.purple },
  Keyword = { fg = p.purple, bold = true },
  Exception = { fg = p.purple, bold = true },
  Operator = { fg = p.cyan },
  Delimiter = { fg = p.gray },
  PreProc = { fg = p.pink },
  Include = { fg = p.pink },
  Define = { fg = p.pink },
  Macro = { fg = p.pink },
  PreCondit = { fg = p.pink },
  Type = { fg = p.yellow },
  StorageClass = { fg = p.yellow, italic = true },
  Structure = { fg = p.yellow },
  Typedef = { fg = p.yellow },
  Special = { fg = p.cyan },
  SpecialChar = { fg = p.cyan },
  Tag = { fg = p.cyan },
  Debug = { fg = p.cyan },
  Underlined = { fg = p.blue, underline = true },
  Ignore = { fg = p.faint },
  Error = { fg = p.red, bold = true },
  Added = { fg = p.green },
  Changed = { fg = p.blue },
  Removed = { fg = p.red },

  -- Tree-sitter
  ["@variable"] = { fg = p.white },
  ["@variable.builtin"] = { fg = p.red, italic = true },
  ["@variable.parameter"] = { fg = p.orange, italic = true },
  ["@variable.member"] = { fg = p.dim },
  ["@property"] = { fg = p.dim },
  ["@constant"] = { link = "Constant" },
  ["@constant.builtin"] = { fg = p.orange, italic = true },
  ["@constant.macro"] = { fg = p.pink },
  ["@module"] = { fg = p.yellow },
  ["@label"] = { link = "Label" },
  ["@string"] = { link = "String" },
  ["@string.escape"] = { fg = p.cyan },
  ["@character"] = { link = "Character" },
  ["@number"] = { link = "Number" },
  ["@boolean"] = { link = "Boolean" },
  ["@type"] = { link = "Type" },
  ["@type.builtin"] = { fg = p.yellow, italic = true },
  ["@type.definition"] = { fg = p.yellow },
  ["@attribute"] = { fg = p.cyan },
  ["@function"] = { link = "Function" },
  ["@function.call"] = { fg = p.blue },
  ["@function.builtin"] = { fg = p.blue, italic = true },
  ["@function.macro"] = { fg = p.pink },
  ["@keyword"] = { link = "Keyword" },
  ["@keyword.return"] = { fg = p.purple, bold = true },
  ["@keyword.directive"] = { fg = p.pink },
  ["@keyword.directive.define"] = { fg = p.pink },
  ["@keyword.import"] = { fg = p.pink },
  ["@keyword.modifier"] = { fg = p.yellow, italic = true },
  ["@keyword.type"] = { fg = p.yellow },
  ["@operator"] = { link = "Operator" },
  ["@punctuation"] = { fg = p.gray },
  ["@comment"] = { link = "Comment" },
  ["@comment.todo"] = { link = "Todo" },

  -- LSP
  ["@lsp.type.macro"] = { fg = p.pink },
  ["@lsp.type.enumMember"] = { fg = p.orange },
  LspReferenceText = { bg = p.line },
  LspReferenceRead = { bg = p.line },
  LspReferenceWrite = { bg = p.line, underline = true },
  LspInlayHint = { fg = p.faint, italic = true },
  DiagnosticError = { fg = p.red },
  DiagnosticWarn = { fg = p.yellow },
  DiagnosticInfo = { fg = p.blue },
  DiagnosticHint = { fg = p.cyan },
  DiagnosticOk = { fg = p.green },
  DiagnosticVirtualTextError = { fg = p.red, italic = true },
  DiagnosticVirtualTextWarn = { fg = p.yellow, italic = true },
  DiagnosticVirtualTextInfo = { fg = p.blue, italic = true },
  DiagnosticVirtualTextHint = { fg = p.cyan, italic = true },
  DiagnosticUnderlineError = { undercurl = true, sp = p.red },
  DiagnosticUnderlineWarn = { undercurl = true, sp = p.yellow },
  DiagnosticUnderlineInfo = { undercurl = true, sp = p.blue },
  DiagnosticUnderlineHint = { undercurl = true, sp = p.cyan },

  -- Plugins
  BlinkCmpLabelMatch = { fg = p.blue, bold = true },
  BlinkCmpKind = { fg = p.purple },
  BlinkCmpMenuBorder = { link = "FloatBorder" },
  BlinkCmpDocBorder = { link = "FloatBorder" },
  IblIndent = { fg = p.guide },
  IblScope = { fg = p.faint },
  RainbowDelimiterRed = { fg = p.yellow },
  RainbowDelimiterYellow = { fg = p.purple },
  RainbowDelimiterBlue = { fg = p.blue },
  RainbowDelimiterOrange = { fg = p.orange },
  RainbowDelimiterGreen = { fg = p.green },
  RainbowDelimiterViolet = { fg = p.pink },
  RainbowDelimiterCyan = { fg = p.cyan },
  GitSignsAdd = { fg = p.green },
  GitSignsChange = { fg = p.blue },
  GitSignsDelete = { fg = p.red },
  NvimTreeNormal = { bg = none },
  NvimTreeWinSeparator = { link = "WinSeparator" },
  NvimTreeRootFolder = { fg = p.purple, bold = true },
  NvimTreeFolderName = { fg = p.blue },
  NvimTreeOpenedFolderName = { fg = p.blue, bold = true },
  NvimTreeFolderIcon = { fg = p.blue },
  NvimTreeIndentMarker = { fg = p.guide },
  FzfLuaBorder = { link = "FloatBorder" },
}

for name, spec in pairs(groups) do
  vim.api.nvim_set_hl(0, name, spec)
end
