-- vimesimal — monochrome theme matching kitty, with muted syntax accents.
-- Background is NONE so kitty's background_opacity shows through.

vim.cmd("highlight clear")
vim.o.background = "dark"
vim.g.colors_name = "vimesimal"

local p = require("vimesimal.palette")
local none = "NONE"

local groups = {
  -- Editor UI
  Normal = { fg = p.white, bg = none },
  NormalNC = { link = "Normal" },
  NormalFloat = { fg = p.dim, bg = p.panel },
  FloatBorder = { fg = p.faint, bg = p.panel },
  FloatTitle = { fg = p.white, bg = p.panel, bold = true },
  NonText = { fg = p.guide },
  Whitespace = { fg = p.guide },
  SpecialKey = { fg = p.guide },
  EndOfBuffer = { fg = p.guide },
  Conceal = { fg = p.faint },
  LineNr = { fg = p.faint },
  CursorLineNr = { fg = p.white, bg = p.panel, bold = true },
  CursorLine = { bg = p.panel },
  CursorColumn = { bg = p.panel },
  ColorColumn = { bg = p.panel },
  SignColumn = { bg = none },
  FoldColumn = { fg = p.faint },
  Folded = { fg = p.mute, bg = p.panel },
  WinSeparator = { fg = p.guide },
  StatusLine = { fg = p.white, bg = p.panel },
  StatusLineNC = { fg = p.faint, bg = p.panel },
  TabLine = { fg = p.faint, bg = p.panel },
  TabLineFill = { bg = p.panel },
  TabLineSel = { fg = p.black, bg = p.white, bold = true },
  WinBar = { fg = p.dim },
  Visual = { fg = p.black, bg = p.white },
  Search = { fg = p.black, bg = p.dim },
  IncSearch = { fg = p.black, bg = p.white, bold = true },
  CurSearch = { link = "IncSearch" },
  Substitute = { fg = p.black, bg = p.sand },
  MatchParen = { fg = p.white, bg = p.guide, bold = true },
  Pmenu = { fg = p.dim, bg = p.panel },
  PmenuSel = { fg = p.black, bg = p.white, bold = true },
  PmenuSbar = { bg = p.line },
  PmenuThumb = { bg = p.mute },
  PmenuKind = { fg = p.steel, bg = p.panel },
  PmenuExtra = { fg = p.mute, bg = p.panel },
  WildMenu = { link = "PmenuSel" },
  Title = { fg = p.white, bold = true },
  Directory = { fg = p.steel },
  ModeMsg = { fg = p.white, bold = true },
  MoreMsg = { fg = p.sage },
  Question = { fg = p.sage },
  ErrorMsg = { fg = p.red, bold = true },
  WarningMsg = { fg = p.sand },
  QuickFixLine = { bg = p.line },
  SpellBad = { undercurl = true, sp = p.red },
  SpellCap = { undercurl = true, sp = p.sand },
  SpellRare = { undercurl = true, sp = p.mauve },
  SpellLocal = { undercurl = true, sp = p.steel },
  DiffAdd = { fg = p.sage, bg = p.panel },
  DiffChange = { fg = p.steel, bg = p.panel },
  DiffDelete = { fg = p.red },
  DiffText = { fg = p.black, bg = p.steel },
  Cursor = { reverse = true },

  -- Syntax
  Comment = { fg = p.mute, italic = true },
  SpecialComment = { fg = p.faint, italic = true },
  Todo = { fg = p.black, bg = p.sand, bold = true },
  Constant = { fg = p.rose },
  Number = { fg = p.rose },
  Float = { fg = p.rose },
  Boolean = { fg = p.rose },
  String = { fg = p.sand },
  Character = { fg = p.sand },
  Identifier = { fg = p.white },
  Function = { fg = p.white, bold = true },
  Statement = { fg = p.steel, bold = true },
  Conditional = { fg = p.steel, bold = true },
  Repeat = { fg = p.steel, bold = true },
  Label = { fg = p.steel },
  Keyword = { fg = p.steel, bold = true },
  Exception = { fg = p.steel, bold = true },
  Operator = { fg = p.gray },
  Delimiter = { fg = p.gray },
  PreProc = { fg = p.mauve },
  Include = { fg = p.mauve },
  Define = { fg = p.mauve },
  Macro = { fg = p.mauve },
  PreCondit = { fg = p.mauve },
  Type = { fg = p.sage },
  StorageClass = { fg = p.sage, italic = true },
  Structure = { fg = p.sage },
  Typedef = { fg = p.sage },
  Special = { fg = p.teal },
  SpecialChar = { fg = p.teal },
  Tag = { fg = p.teal },
  Debug = { fg = p.teal },
  Underlined = { fg = p.steel, underline = true },
  Ignore = { fg = p.faint },
  Error = { fg = p.red, bold = true },
  Added = { fg = p.sage },
  Changed = { fg = p.steel },
  Removed = { fg = p.red },

  -- Tree-sitter
  ["@variable"] = { fg = p.white },
  ["@variable.builtin"] = { fg = p.rose, italic = true },
  ["@variable.parameter"] = { fg = p.dim, italic = true },
  ["@variable.member"] = { fg = p.dim },
  ["@property"] = { fg = p.dim },
  ["@constant"] = { link = "Constant" },
  ["@constant.builtin"] = { fg = p.rose, italic = true },
  ["@constant.macro"] = { fg = p.mauve },
  ["@module"] = { fg = p.sage },
  ["@label"] = { link = "Label" },
  ["@string"] = { link = "String" },
  ["@string.escape"] = { fg = p.teal },
  ["@character"] = { link = "Character" },
  ["@number"] = { link = "Number" },
  ["@boolean"] = { link = "Boolean" },
  ["@type"] = { link = "Type" },
  ["@type.builtin"] = { fg = p.sage, italic = true },
  ["@type.definition"] = { fg = p.sage },
  ["@attribute"] = { fg = p.teal },
  ["@function"] = { link = "Function" },
  ["@function.call"] = { fg = p.white },
  ["@function.builtin"] = { fg = p.white, italic = true },
  ["@function.macro"] = { fg = p.mauve },
  ["@keyword"] = { link = "Keyword" },
  ["@keyword.return"] = { fg = p.steel, bold = true },
  ["@keyword.directive"] = { fg = p.mauve },
  ["@keyword.directive.define"] = { fg = p.mauve },
  ["@keyword.import"] = { fg = p.mauve },
  ["@keyword.modifier"] = { fg = p.sage, italic = true },
  ["@keyword.type"] = { fg = p.sage },
  ["@operator"] = { link = "Operator" },
  ["@punctuation"] = { fg = p.gray },
  ["@comment"] = { link = "Comment" },
  ["@comment.todo"] = { link = "Todo" },

  -- LSP
  ["@lsp.type.macro"] = { fg = p.mauve },
  ["@lsp.type.enumMember"] = { fg = p.rose },
  LspReferenceText = { bg = p.line },
  LspReferenceRead = { bg = p.line },
  LspReferenceWrite = { bg = p.line, underline = true },
  LspInlayHint = { fg = p.faint, italic = true },
  DiagnosticError = { fg = p.red },
  DiagnosticWarn = { fg = p.sand },
  DiagnosticInfo = { fg = p.steel },
  DiagnosticHint = { fg = p.mute },
  DiagnosticOk = { fg = p.sage },
  DiagnosticVirtualTextError = { fg = p.red, italic = true },
  DiagnosticVirtualTextWarn = { fg = p.sand, italic = true },
  DiagnosticVirtualTextInfo = { fg = p.steel, italic = true },
  DiagnosticVirtualTextHint = { fg = p.mute, italic = true },
  DiagnosticUnderlineError = { undercurl = true, sp = p.red },
  DiagnosticUnderlineWarn = { undercurl = true, sp = p.sand },
  DiagnosticUnderlineInfo = { undercurl = true, sp = p.steel },
  DiagnosticUnderlineHint = { undercurl = true, sp = p.mute },

  -- Plugins
  BlinkCmpLabelMatch = { fg = p.white, bold = true },
  BlinkCmpKind = { fg = p.steel },
  BlinkCmpMenuBorder = { link = "FloatBorder" },
  BlinkCmpDocBorder = { link = "FloatBorder" },
  IblIndent = { fg = p.guide },
  IblScope = { fg = p.faint },
  RainbowDelimiterRed = { fg = p.dim },
  RainbowDelimiterYellow = { fg = p.steel },
  RainbowDelimiterBlue = { fg = p.sand },
  RainbowDelimiterOrange = { fg = p.sage },
  RainbowDelimiterGreen = { fg = p.mauve },
  RainbowDelimiterViolet = { fg = p.teal },
  RainbowDelimiterCyan = { fg = p.rose },
  GitSignsAdd = { fg = p.sage },
  GitSignsChange = { fg = p.steel },
  GitSignsDelete = { fg = p.red },
  NvimTreeNormal = { bg = none },
  NvimTreeWinSeparator = { link = "WinSeparator" },
  NvimTreeRootFolder = { fg = p.faint, bold = true },
  NvimTreeFolderName = { fg = p.steel },
  NvimTreeOpenedFolderName = { fg = p.steel, bold = true },
  NvimTreeFolderIcon = { fg = p.steel },
  NvimTreeIndentMarker = { fg = p.guide },
  FzfLuaBorder = { link = "FloatBorder" },
}

for name, spec in pairs(groups) do
  vim.api.nvim_set_hl(0, name, spec)
end
